[package]
name = "doing-some-actors"
version = "0.1.0"
authors = ["sergey-melnychuk"]
edition = "2018"

[dependencies]
core_affinity = "0.5.10"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "workload"
harness = false
